repos:
-   repo: local
    hooks:
    -   id: Run cs-fixer
        name: Run cs-fixer
        entry: sh cs-fixer.sh
        language: system
        always_run: true
        pass_filenames: false

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
